version: '3.8'

services:
  # Orquestrador - API Gateway
  orchestrator-api:
    build:
      context: ../askadb-orchestrator-api
    container_name: askadb-orchestrator-api
    ports:
      - "8000:8000"
    depends_on:
      - nl-query
      - query-engine
      - dashboard-core
    environment:
      - FASTAPI_ENV=development
    networks:
      - askadb-network

  # Serviço de Linguagem Natural
  nl-query:
    build:
      context: ../askadb-nl-query
    container_name: askadb-nl-query
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FASTAPI_ENV=development
    networks:
      - askadb-network

  # Query Engine - Core do Banco
  query-engine:
    build:
      context: ../askadb-query-engine
    container_name: askadb-query-engine
    ports:
      - "8002:8002"
    volumes:
      - query_data:/app/data
    environment:
      - RUST_LOG=info
    init: true
    restart: unless-stopped
    networks:
      - askadb-network

  # Dashboard Core - Auto-charting
  dashboard-core:
    build:
      context: ../askadb-dashboard-core
    container_name: askadb-dashboard-core
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
    networks:
      - askadb-network

  # Interface Web
  ui:
    build:
      context: ../askadb-ui
    container_name: askadb-ui
    ports:
      - "3000:80"
    depends_on:
      - orchestrator-api
    networks:
      - askadb-network

networks:
  askadb-network:
    driver: bridge

volumes:
  query_data:
